// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggnxqhfncmipmczgsrzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbnhxaGZuY21pcG1jemdzcnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NDc5NjQsImV4cCI6MjA5NDAyMzk2NH0.KAtNd6BgLIZymYTf2nX3MnwArGbTa0Asc57N6pv2bpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});