// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smyzmoalnjhqdzalbdzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteXptb2FsbmpocWR6YWxiZHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NjAzNTMsImV4cCI6MjA4NzQzNjM1M30.M5ov6fXiq1wyoXXJGh8rrK0hF8DnDx1OBa-ynN9mSR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});